use deadpool::managed::Object;
use deadpool_postgres::Manager;
use postgres::Row;
use serde::Deserialize;

#[derive(Debug, Deserialize)]
/// Struct representing an item on the misc index page.
struct MiscItem {
    /// The DB ID, autogenerated by the DB itself.
    pub id: i32,

    /// The url this item is pointing towards.
    pub url: String,

    /// The name of this item.
    pub title: String,

    /// A short description of the contents of this item
    pub description: String,
    // TODO: Handle to implement urls
    /// The index of this item in the page.
    pub order_position: i32,
}

impl MiscItem {
    // Returns a string pointing towards the thumbnail of this item.
    fn get_thumbnail_url(&self) -> String {
        todo!()
    }

    /// Returns all MiscItems in the DB, sorted.
    pub async fn get_all(db_connection: &Object<Manager>) -> Vec<Self> {
        let requested_category_rows = db_connection
            .query("SELECT * FROM misc", &[])
            .await
            .unwrap();

        let mut requested_categories: Vec<Self> = requested_category_rows
            .iter()
            .map(Self::from_db_row)
            .collect();

        requested_categories.sort_by_key(|category| category.order_position);

        requested_categories
    }

    /// Converts a DB row with the relevant info to a MiscItem struct.
    fn from_db_row(row: &Row) -> Self {
        Self {
            id: row.get("id"),
            order_position: row.get("order_position"),
            title: row.get("title"),
            description: row.get("description"),
            url: row.get("url"),
        }
    }
}
